all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B183333/Hello
#	java -classpath "../.." s4.B183333/Frequencer
#	java -classpath "../.." s4.B183333/InformationEstimator
	java -classpath "../.." s4.B183333/TestCase
