all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B183325/Hello
#	java -classpath "../.." s4.B183325/Frequencer
#	java -classpath "../.." s4.B183325/InformationEstimator
	java -classpath "../.." s4.B183325/TestCase
