all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B183328/Hello
#	java -classpath "../.." s4.B183328/Frequencer
#	java -classpath "../.." s4.B183328/InformationEstimator
	java -classpath "../.." s4.B183328/TestCase
