all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B183310/Hello
#	java -classpath "../.." s4.B183310/Frequencer
#	java -classpath "../.." s4.B183310/InformationEstimator
	java -classpath "../.." s4.B183310/TestCase
