all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B183367/Hello
#	java -classpath "../.." s4.B183367/Frequencer
#	java -classpath "../.." s4.B183367/InformationEstimator
	java -classpath "../.." s4.B183367/TestCase
