all:
	javac Hello.java -classpath "../.."
	javac Frequencer.java -classpath "../.."
	javac InformationEstimator.java -classpath "../.."
	javac TestCase.java -classpath "../.."
run:
#	java -classpath "../.." s4.B161305/Hello
#	java -classpath "../.." s4.B161305/Frequencer
#	java -classpath "../.." s4.B161305/InformationEstimator
	java -classpath "../.." s4.B161305/TestCase
